### ISSUE TITLE
Support for Scarlett 6i6

### ISSUE THREAD

**Issue by chetwisniewski** [fulup-bzh/AlsaJsonMixer#1]
See AJG config dump at https://cloud.zuzax.com/index.php/s/pimzY4kvz3hRVdP

**Comment by fulup-bzh** [comment]
Hoops!!! File on cloud.zuzax as a null size. Look like the upload went wrong.

**Comment by chetwisniewski** [comment]
Sorry about that, I reuploaded it.

Chester

**Comment by fulup-bzh** [comment]
Looks much better, thank you

**Comment by fulup-bzh** [comment]
I integrated AlsaMixer GIT from your JSON config.
After updating your AlsaJsonMixer repository you should be able to select the 6i6. If driver is compatible with the other Scarlett then it should work :)

**Comment by chetwisniewski** [comment]
Brilliant, works great. Thanks for your help.
